//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepDrivesAlive.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastSettingsWindowStateSaved {
            get {
                return ((bool)(this["LastSettingsWindowStateSaved"]));
            }
            set {
                this["LastSettingsWindowStateSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LastSettingsWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["LastSettingsWindowLocation"]));
            }
            set {
                this["LastSettingsWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LastSettingsWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["LastSettingsWindowSize"]));
            }
            set {
                this["LastSettingsWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState LastSettingsWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["LastSettingsWindowState"]));
            }
            set {
                this["LastSettingsWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastMonitorWindowStateSaved {
            get {
                return ((bool)(this["LastMonitorWindowStateSaved"]));
            }
            set {
                this["LastMonitorWindowStateSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LastMonitorWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["LastMonitorWindowLocation"]));
            }
            set {
                this["LastMonitorWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size LastMonitorWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["LastMonitorWindowSize"]));
            }
            set {
                this["LastMonitorWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState LastMonitorWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["LastMonitorWindowState"]));
            }
            set {
                this["LastMonitorWindowState"] = value;
            }
        }
    }
}
